      
      
# Credenciais AWS
spring.cloud.aws.credentials.access-key=
spring.cloud.aws.credentials.secret-key=
spring.cloud.aws.region.static=us-east-1

# Nome da sua fila (Criada na Fase 2)
queue.order-events=
