      
      
# Credenciais AWS
spring.cloud.aws.credentials.access-key=SUA_ACCESS_KEY
spring.cloud.aws.credentials.secret-key=SUA_SECRET_KEY
spring.cloud.aws.region.static=us-east-1

# Nome da sua fila (Criada na Fase 2)
queue.order-events=T0XN_SEU_NOME_PEDIDOS.fifo
    
    